export const CONFIG = {
  WORLD_RESOLUTION: 15,
  INITIAL_GRAZERS: 50,
  INITIAL_HUNTERS: 5,

  GRAZER: {
    MAX_SPEED: 1.8,
    MAX_FORCE: 0.1,
    INITIAL_ENERGY: 100,
    REPRODUCTION_ENERGY: 180,
    FLEE_RADIUS: 80,
  },

  HUNTER: {
    MAX_SPEED: 2.8,
    MAX_FORCE: 0.25,
    INITIAL_ENERGY: 150,
    REPRODUCTION_ENERGY: 300,
    HUNT_RADIUS: 150,
  },

  QUADTREE_CAPACITY: 4,
};
